### PR TITLE
Implement granularity control

### LINKED ISSUE #3: Add configurable granularity
I love this, thanks! It mimics the functionality I love from https://github.com/irzyxa/Volume2 that I use on Windows.

The main thing I'm missing though is that this hard-codes the volume granularity at 5%. I'd like to have it at 2% per scroll tick instead.

I'd love it if simple settings for the plugin could be added to configure this!

### PR DESCRIPTION
**Pull request by francislavoie**
Fix #3 

I was bored tonight, so I decided to try to scratch my own itch.

This enables preferences for the extension, and adds a Granularity option which is a percentage step to increase/decrease the volume. Defaults to 5 which is the same as before. I like 2, personally.

image

You'll notice there's a binary file, I just followed the guide on https://gjs.guide/extensions/development/preferences.html#creating-the-schema which says we need to compile the prefs XML schema with the below command (if you want to verify that it matches on your system in case you don't trust the binary):

```
glib-compile-schemas volume_scroller@trflynn89.pm.me/schemas/
```

### CODE REVIEW

**Comment by trflynn89** [comment]
Thanks! I'm just getting back from vacation, so I'll take a look at this once I've gotten things settled :)

**Comment by francislavoie** [comment]
@trflynn89 any chance you could look at this again?

**Comment by francislavoie** [comment]
Bump again? :blush:

**Comment by francislavoie** [comment]
Happy new year!

Is there anything else I can do to help this get merged?

**Pull request closed without merging**
